### ISSUE TITLE
Update versioneer

### ISSUE THREAD

**Issue by jamesjer** [matthew-brett/nb2plots#18]
The Fedora project is doing test builds of  python packages with the current alpha version of python3.11.  The version of versioneer.py in nb2plots is too old; it uses SafeConfigParser, which was deprecated in python 3.2 and has been removed entirely from python 3.11.  This has been fixed in recent versions of versioneer.

**Comment by kloczek** [comment]
Looking on https://github.com/matthew-brett/nb2plots/compare/0.6...master I think that it wound be really good to flush all those commits as new release.
Any plans to do that soon? 🤔

**Comment by matthew-brett** [comment]
Yes, can do.   Remind me if you don't see the release in the next few days.

**Comment by matthew-brett** [comment]
Done.  Does it work as expected?

**Comment by jamesjer** [comment]
Yes, it works as I expect, at least.  Thank you!

**Comment by matthew-brett** [comment]
Thanks - closing - please re-open if you find a problem.
