### ISSUE TITLE
nbconvert 7.9 has no attribute 'exporter'

### ISSUE THREAD

**Issue by jarrodmillman** [matthew-brett/nb2plots#32]
In NX, we are getting this error with the newly released version of nbconvert:
```
Extension error (nb2plots.runroles):
Handler <function write_runfiles at 0x7fa5ad52bf40> for event 'build-finished' threw an exception (exception: module 'nbconvert' has no attribute 'exporter')
```

**Comment by jarrodmillman** [comment]
See https://github.com/networkx/networkx/pull/6981#issuecomment-1747433956

**Comment by matthew-brett** [comment]
I think this is an API change in the very-recent `nbconvert` release - see: https://github.com/jupyter/nbconvert/issues/2054

**Comment by blink1073** [comment]
I'm confused, there was no `nbconvert.exporter` in 7.8.0 or even 7.0.0 for that matter:

```python
Successfully installed lxml-4.9.3 mistune-2.0.5 nbconvert-7.0.0
(34dbfd366420283b353b688a) ➜  ~ python -c "from nbconvert.exporter import *"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'nbconvert.exporter'
```

**Comment by blink1073** [comment]
There also was not a `ResourceDict` in the repo anywhere in 7.8.0.

**Comment by blink1073** [comment]
Ah, it is `ResourcesDict`.  I see what the ask is, I'll take it over to https://github.com/jupyter/nbconvert/issues/2054.
