### ISSUE TITLE
Option to disable timeout in `code_links:: full` execution

### ISSUE THREAD

**Issue by jni** [matthew-brett/nb2plots#5]
Hi and thanks for a great package! (Thanks @stefanv for pointing it out to me.)

I'm using nb2plots to generate documentation that contains a moderately long-running cell (1-2min), and it is timing out when rebuilding the notebook from the rst. I tried changing my ipython_config.py but to no avail. Any suggestions?

**Comment by matthew-brett** [comment]
Ouch - that's annoying.   The relevant code is in `nb2plots/runroles.py:fill_notebook`.  I think it's just a question of adding a `timeout=120` keyword to the call there to ExecutePreprocessor, if you want a quick hack (does that work)?

The obvious thing would be to have that as a configuration option...

**Comment by matthew-brett** [comment]
Just thinking aloud, but it would also be possible to add an option to the `fullnotebook` role (which `code-links` uses).  It would work like this (I think):

```
.. role:: longerfullnotebook(fullnotebook)
   :timeout: 120
```

That goes in your .rst file.  Then we'd have to a) plumb in the option parsing, b) add that as an option to the codelinks directive, or allow any named role for the codelinks directive.

Sorry, I'm just negotiating with myself about the best option(s).

**Comment by matthew-brett** [comment]
Or, add the timeout option to the codelinks directive.  Or all three.

**Comment by jni** [comment]
Thanks! Quick hacks are useful. =)

I'm not at all familiar with sphinx directives, so I don't now what the most "sphinxonic" version would be, but the codelinks directive and the nbplot sphinx configuration options are the places I would have looked.

Incidentally, do you have a Makefile example for running nb2plots during make html? I didn't notice it in your teaching repo. Specifically, currently I'm doing

```
nb2plots getting_started.ipynb > getting_started.rst; echo ..code_links:: >> getting_started.rst
```

before `make html`. Can I eliminate this step somehow? And if so, is that documented somewhere?

**Comment by matthew-brett** [comment]
I haven't really automated that step myself, because I use the nb2plots command once, to port the notebook into .rst, rather than keeping the notebook as source.  The conversion is reasonably good, but as notebooks get more complex, there are enough annoyances that I like my hand-edited .rst better.  But - automating it would probably be useful.

**Comment by matthew-brett** [comment]
@jni - I just added all the timeout features above to the master branch.  For example, you can now set:

```
fill_notebook_timeout = -1
```

in the conf file, to have infinite timeout.  

You can also add `timeout` as an option to the `code-links` directive:

```
.. code-links:
    :timeout: -1
```

Does it work for you?

**Comment by jni** [comment]
Yes! Perfectly! Thank you! =) It would be good to add this to the docs somewhere, maybe in the `code-links` page?

**Comment by matthew-brett** [comment]
I made a new release with this feature, docs (as your suggestion) at http://matthew-brett.github.io/nb2plots/code_links.html

**Comment by jni** [comment]
Perfect! Thank you very much!
