### ISSUE TITLE
Show high-resolution plots inline

### ISSUE THREAD

**Issue by jni** [matthew-brett/nb2plots#6]
Some of my plots look terrible with nbplots. I tried setting

```python
nbplot_rcparams = {'figure.dpi': 150, 'savefig.dpi': 150}
plot_rcparams = {'figure.dpi': 150, 'savefig.dpi': 150}
```

in my conf.py, to no avail. How do I ensure I get a high resolution image in my documentation pages?

**Comment by matthew-brett** [comment]
Hi - I think you want the `nbplot_formats` configuration variable.  Maybe something like:

```
nbplot_formats = [('png', 150), ('hires.png', 300)]
```

See: http://matthew-brett.github.io/nb2plots/nbplots.html#module-nb2plots.nbplots - though the docs could do with examples.

**Comment by matthew-brett** [comment]
OK to close this issue?

**Comment by jni** [comment]
I haven't had a chance to test this but it seems like what I need, thank you!
